// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dbLayer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	Commentid       int32
	Comment         pgtype.Text
	Publishedtime   pgtype.Timestamp
	Parentcommentid pgtype.Int4
	Urlstring       pgtype.Text
}
